# Generated by Django 4.1.4 on 2023-01-20 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('controler',models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_method_controler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('company_threshold', models.IntegerField(default=6000)),
                ('branch_threshold', models.IntegerField(default=1000)),
                ('process_threshold', models.IntegerField(default=500)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.company')),
                ('controler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_controler', to=settings.AUTH_USER_MODEL)),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.purchase_type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=17, unique=True)),
                ('date', models.DateField(auto_now=True)),
                ('product', models.CharField(max_length=17)),
                ('price', models.IntegerField()),
                ('asker_comment', models.TextField(blank=True, max_length=100)),
                ('vendor', models.CharField(max_length=17)),
                ('unit_price', models.IntegerField(blank=True)),
                ('delivery_date', models.DateField()),
                ('controler_auth', models.CharField(choices=[('Authorized', 'Authorized'), ('Refused', 'Refused'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('controler_comment', models.TextField(blank=True, max_length=100)),
                ('asker_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.branch')),
                ('controler_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_controler', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.payment_method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.process')),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.purchase_type')),
            ],
        ),
    ]
