# Generated by Django 4.1.4 on 2022-12-21 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('controler_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('threshold_1', models.IntegerField()),
                ('threshold_2', models.IntegerField()),
                ('threshold_3', models.IntegerField()),
                ('controler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('super_controler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.branch')),
                ('controler_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=17, unique=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.CharField(max_length=17)),
                ('price', models.IntegerField()),
                ('asker_comment', models.CharField(max_length=254, null=True)),
                ('vendor', models.CharField(max_length=17)),
                ('unit_price', models.IntegerField(null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('controler_auth', models.CharField(choices=[('Authorized', 'Authorized'), ('Refused', 'Refused'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('controler_comment', models.CharField(max_length=254, null=True)),
                ('asker_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.branch')),
                ('controler_login', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controler', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.payment_method')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.process')),
                ('purchase_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases_auth.purchase_type')),
            ],
        ),
    ]
