# Generated by Django 4.1.4 on 2022-12-16 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth_datas',
            name='user_login',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases_auth.auth_users'),
        ),
    ]
