# Generated by Django 4.1.4 on 2022-12-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='asker_login',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datas',
            name='controler_auth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datas',
            name='controler_login',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datas',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
