# Generated by Django 4.1.4 on 2022-12-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_auth', '0003_alter_datas_controler_auth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='controler_auth',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('REFUSED', 'Refused'), ('PENDING', 'Pending')], max_length=10),
        ),
    ]
