# Generated by Django 4.1.4 on 2022-12-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_auth', '0004_alter_datas_controler_auth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='datas',
            name='asker_login',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datas',
            name='controler_auth',
            field=models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('REFUSED', 'Refused'), ('PENDING', 'Pending')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='datas',
            name='controler_login',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='datas',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
