# Generated by Django 4.1.4 on 2022-12-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases_auth', '0006_users_email_users_first_name_users_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datas',
            new_name='Auth_datas',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='Auth_users',
        ),
    ]
